// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2l7x70dKO-cxs79TeyK7F76IaG4PaNwU',
    appId: '1:470237294780:web:9b997e899b044cd951a0b9',
    messagingSenderId: '470237294780',
    projectId: 'zircon-chat-d8fc7',
    authDomain: 'zircon-chat-d8fc7.firebaseapp.com',
    storageBucket: 'zircon-chat-d8fc7.appspot.com',
    measurementId: 'G-CBBVVEQ5E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmtsS5Wu-uQR4pmcYsHTDU3rUsOh_r0iY',
    appId: '1:470237294780:android:3a37919b652d770d51a0b9',
    messagingSenderId: '470237294780',
    projectId: 'zircon-chat-d8fc7',
    storageBucket: 'zircon-chat-d8fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzpOPrrfxJJLE64tBx49aYk2rnbN70Z-s',
    appId: '1:470237294780:ios:4c80314169ce876f51a0b9',
    messagingSenderId: '470237294780',
    projectId: 'zircon-chat-d8fc7',
    storageBucket: 'zircon-chat-d8fc7.appspot.com',
    iosClientId: '470237294780-2tndl0c23hoae62qmu2he5bfcas370qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzpOPrrfxJJLE64tBx49aYk2rnbN70Z-s',
    appId: '1:470237294780:ios:4c80314169ce876f51a0b9',
    messagingSenderId: '470237294780',
    projectId: 'zircon-chat-d8fc7',
    storageBucket: 'zircon-chat-d8fc7.appspot.com',
    iosClientId: '470237294780-2tndl0c23hoae62qmu2he5bfcas370qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
